# Generated by Django 2.0.1 on 2018-08-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('greeting', models.CharField(max_length=200)),
            ],
        ),
    ]
